"""
Image Generation API - Tier-Based Pipeline.

FREE Tier:
    User → Llama 3.3 FREE (enhance) → LongCat Flash FREE → Image
    
JIVE/JIGGA Tier:
    User → Llama 3.3 FREE (enhance) → FLUX 1.1 Pro → Image

Prompt enhancement is ALWAYS via OpenRouter Llama 3.3 70B FREE.
"""

import logging
from typing import Any

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

from app.core.router import UserTier, IMAGE_LIMITS, is_image_prompt
from app.services.image_service import image_service
from app.services.openrouter_service import openrouter_service

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/images", tags=["Images"])


class ImageGenerateRequest(BaseModel):
    """Request body for image generation."""
    prompt: str = Field(
        ...,
        min_length=1,
        max_length=4000,
        description="Text description of the desired image"
    )
    user_id: str | None = Field(default=None)
    user_tier: UserTier = Field(
        default=UserTier.FREE,
        description="User's subscription tier (free, jive, jigga)"
    )
    size: str = Field(
        default="1024x1024",
        description="Image dimensions (FLUX only)",
        pattern=r"^\d+x\d+$"
    )
    enhance_prompt: bool = Field(
        default=True,
        description="Use Llama 3.3 70B to enhance prompt before generation"
    )


class ImageGenerateResponse(BaseModel):
    """Response body for image generation."""
    success: bool = True
    original_prompt: str
    enhanced_prompt: str
    image_data: str  # Base64 for FLUX, content for LongCat
    size: str | None = None
    meta: dict[str, Any] = {}


@router.post(
    "/generate",
    response_model=ImageGenerateResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate an image based on user tier"
)
async def generate_image(request: ImageGenerateRequest) -> ImageGenerateResponse:
    """
    Generate an image based on user tier.
    
    **FREE Tier:**
    - Prompt enhanced by Llama 3.3 70B FREE
    - Image generated by LongCat Flash FREE
    - Limit: 50 images/month
    
    **JIVE Tier:**
    - Prompt enhanced by Llama 3.3 70B FREE
    - Image generated by FLUX 1.1 Pro
    - Limit: 200 images/month
    
    **JIGGA Tier:**
    - Prompt enhanced by Llama 3.3 70B FREE
    - Image generated by FLUX 1.1 Pro
    - Limit: 1000 images/month
    """
    try:
        result = await image_service.generate_image(
            prompt=request.prompt,
            user_id=request.user_id,
            user_tier=request.user_tier,
            size=request.size,
            enhance_prompt=request.enhance_prompt,
        )
        
        return ImageGenerateResponse(
            success=True,
            original_prompt=result.original_prompt,
            enhanced_prompt=result.enhanced_prompt,
            image_data=result.image_data,
            size=result.size,
            meta=result.meta,
        )
        
    except Exception as e:
        logger.exception("Image generation error")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Image generation failed: {str(e)}"
        )


@router.post(
    "/enhance-prompt",
    summary="Enhance an image prompt (FREE for all tiers)"
)
async def enhance_prompt(prompt: str) -> dict[str, Any]:
    """
    Enhance a prompt using Llama 3.3 70B FREE.
    
    This is FREE for ALL tiers - the universal "Enhance" button.
    
    Returns all three versions: original, structured, enhanced.
    """
    try:
        result = await openrouter_service.enhance_prompt(prompt)
        return {
            "success": True,
            **result
        }
    except Exception as e:
        logger.exception("Prompt enhancement error")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Prompt enhancement failed: {str(e)}"
        )


@router.get(
    "/detect",
    summary="Detect if a prompt is an image request"
)
async def detect_image_intent(prompt: str) -> dict:
    """
    Detect if a prompt is requesting image generation.
    
    Uses keyword matching to route:
    - Image prompts → /api/v1/images/generate
    - Text prompts → /api/v1/chat
    """
    is_image = is_image_prompt(prompt)
    return {
        "prompt": prompt,
        "is_image_request": is_image,
        "suggested_endpoint": "/api/v1/images/generate" if is_image else "/api/v1/chat"
    }


@router.get(
    "/limits",
    summary="Get image generation limits per tier"
)
async def get_limits() -> dict:
    """Get image generation limits for each tier."""
    return {
        "limits": {
            "free": {
                "images_per_month": IMAGE_LIMITS[UserTier.FREE],
                "generator": "LongCat Flash",
                "cost": "FREE"
            },
            "jive": {
                "images_per_month": IMAGE_LIMITS[UserTier.JIVE],
                "generator": "FLUX 1.1 Pro",
                "cost": "Included in subscription"
            },
            "jigga": {
                "images_per_month": IMAGE_LIMITS[UserTier.JIGGA],
                "generator": "FLUX 1.1 Pro",
                "cost": "Included in subscription"
            }
        },
        "prompt_enhancement": {
            "model": "Llama 3.3 70B",
            "provider": "OpenRouter",
            "cost": "FREE (all tiers)"
        }
    }


@router.get(
    "/health",
    summary="Check image service health"
)
async def image_health() -> dict:
    """Check if image services are configured and ready."""
    from app.config import get_settings
    settings = get_settings()
    
    # Check OpenRouter
    openrouter_health = await openrouter_service.health_check()
    
    return {
        "status": "healthy",
        "services": {
            "prompt_enhancement": {
                "provider": "OpenRouter",
                "status": openrouter_health.get("status", "unknown"),
                "model": settings.OPENROUTER_MODEL_LLAMA,
                "cost": "FREE"
            },
            "free_generation": {
                "provider": "OpenRouter",
                "model": settings.OPENROUTER_MODEL_LONGCAT,
                "cost": "FREE"
            },
            "pro_generation": {
                "provider": "DeepInfra",
                "status": "configured" if settings.DEEPINFRA_API_KEY else "unconfigured",
                "model": settings.DEEPINFRA_IMAGE_MODEL
            }
        }
    }
