#!/bin/bash

# Quick IAM Permission Fixer
# Creates a web link for you to grant permissions via Google Cloud Console

PROJECT_ID="general-dev-480621"
SERVICE_ACCOUNT="vertex-express@${PROJECT_ID}.iam.gserviceaccount.com"

echo "🔧 Quick IAM Permission Fix"
echo "=" 
echo ""
echo "✅ Open this link in your browser to grant permissions:"
echo ""
echo "https://console.cloud.google.com/iam-admin/iam?project=${PROJECT_ID}"
echo ""
echo "=" 
echo "Steps in the Console:"
echo "=" 
echo ""
echo "1. Click '+ GRANT ACCESS' button"
echo ""
echo "2. In 'New principals' field, paste:"
echo "   ${SERVICE_ACCOUNT}"
echo ""
echo "3. In 'Select a role' dropdown, add these roles:"
echo "   • Vertex AI User"
echo "   • Service Usage Consumer"
echo ""
echo "4. Click 'SAVE'"
echo ""
echo "5. Wait 1-2 minutes for permissions to propagate"
echo ""
echo "=" 
echo "Alternative: Run these commands if you have gcloud access:"
echo "=" 
echo ""
echo "gcloud projects add-iam-policy-binding ${PROJECT_ID} \\"
echo "  --member=\"serviceAccount:${SERVICE_ACCOUNT}\" \\"
echo "  --role=\"roles/aiplatform.user\""
echo ""
echo "gcloud projects add-iam-policy-binding ${PROJECT_ID} \\"
echo "  --member=\"serviceAccount:${SERVICE_ACCOUNT}\" \\"
echo "  --role=\"roles/serviceusage.serviceUsageConsumer\""
echo ""
echo "=" 
echo "After granting permissions, test with:"
echo "=" 
echo ""
echo "cd /home/ubuntu/Dev-Projects/Gogga/gogga-backend"
echo "./venv_vertex/bin/python test_known_models.py"
echo ""
