#!/bin/bash

echo "🔑 Google Vertex AI Authentication Setup"
echo "========================================"
echo ""
echo "Your API key appears to be a Vertex AI API key, but Vertex AI"
echo "requires OAuth2 authentication, not API keys."
echo ""
echo "Please choose an authentication method:"
echo ""
echo "Option 1: Interactive OAuth2 (Recommended)"
echo "==========================================="
echo "1. Run: source \$HOME/google-cloud-sdk/path.bash.inc"
echo "2. Run: gcloud auth application-default login"
echo "3. Visit the URL shown in your browser"
echo "4. Complete the sign-in process"
echo "5. Then run: ./venv_vertex/bin/python test_deepseek_gcloud.py"
echo ""
echo "Option 2: Service Account JSON Key"
echo "==================================="
echo "1. Download your service account JSON key from:"
echo "   https://console.cloud.google.com/iam-admin/serviceaccounts?project=general-dev-480621"
echo "2. Save it as: ~/vertex-ai-key.json"
echo "3. Run: export GOOGLE_APPLICATION_CREDENTIALS=~/vertex-ai-key.json"
echo "4. Then run: ./venv_vertex/bin/python test_deepseek_gcloud.py"
echo ""
echo "Option 3: Check if DeepSeek is deployed"
echo "========================================"
echo "Visit: https://console.cloud.google.com/vertex-ai/model-garden?project=general-dev-480621"
echo "Search for 'deepseek' and deploy the model if it's not already deployed."
echo ""
echo "After authentication, run the test:"
echo "  cd /home/ubuntu/Dev-Projects/Gogga/gogga-backend"
echo "  ./venv_vertex/bin/python test_deepseek_gcloud.py"
