#!/bin/bash
# =============================================================================
# GOGGA Distributed Setup - Step 5: Deploy Worker Containers
# =============================================================================
# Deploys AI-intensive containers to the worker node (192.168.0.198)
# Updates primary to point to worker for CePO
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
WORKER_IP="192.168.0.198"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DEV_DRIVE="/mnt/dev-drive"
REMOTE_DEV_DRIVE="/home/hybridwolvin/DEV-Drive"

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}  GOGGA Distributed - Deploy Workers${NC}"
echo -e "${BLUE}============================================${NC}"

# =============================================================================
# PREPARE CONFIGURATION ON WORKER
# =============================================================================
echo -e "\n${YELLOW}[1/5]${NC} Copying configuration to worker..."

# Create config directory on DEV-Drive (accessible via NFS)
mkdir -p "$DEV_DRIVE/gogga-config"

# Copy backend env file (contains API keys for CePO)
if [ -f "$PROJECT_ROOT/gogga-backend/.env" ]; then
    cp "$PROJECT_ROOT/gogga-backend/.env" "$DEV_DRIVE/gogga-config/.env"
    echo -e "${GREEN}✓${NC} Backend .env copied to DEV-Drive"
else
    echo -e "${RED}✗${NC} Backend .env not found at $PROJECT_ROOT/gogga-backend/.env"
    exit 1
fi

# Copy docker-compose file for worker
cp "$SCRIPT_DIR/docker-compose.worker.yml" "$DEV_DRIVE/docker/compose/"
echo -e "${GREEN}✓${NC} Docker compose file copied to DEV-Drive"

# =============================================================================
# STOP CEPO ON PRIMARY (will move to worker)
# =============================================================================
echo -e "\n${YELLOW}[2/5]${NC} Stopping CePO on primary (moving to worker)..."
cd "$PROJECT_ROOT"
docker compose stop cepo 2>/dev/null || echo "CePO was not running on primary"
docker compose rm -f cepo 2>/dev/null || true
echo -e "${GREEN}✓${NC} CePO stopped on primary"

# =============================================================================
# DEPLOY CONTAINERS ON WORKER
# =============================================================================
echo -e "\n${YELLOW}[3/5]${NC} Deploying containers on worker..."

# Pull images on worker first
docker --context gogga-worker pull ghcr.io/algorithmicsuperintelligence/optillm:latest-proxy
docker --context gogga-worker pull gcr.io/cadvisor/cadvisor:latest

echo -e "${GREEN}✓${NC} Images pulled on worker"

# Deploy using Docker context
ssh gogga-worker << REMOTE_DEPLOY
set -e
cd ${REMOTE_DEV_DRIVE}/docker/compose
docker compose -f docker-compose.worker.yml up -d
docker compose -f docker-compose.worker.yml ps
REMOTE_DEPLOY

echo -e "${GREEN}✓${NC} Worker containers deployed"

# =============================================================================
# UPDATE PRIMARY TO USE WORKER CEPO
# =============================================================================
echo -e "\n${YELLOW}[4/5]${NC} Updating primary to use worker CePO..."

# Create/update override file for primary
cat > "$PROJECT_ROOT/docker-compose.override.yml" << EOF
# =============================================================================
# GOGGA Docker Compose Override - Distributed Configuration
# =============================================================================
# Generated by distributed setup script
# Points services to worker node at 192.168.0.198
# =============================================================================

services:
  backend:
    environment:
      # Point to CePO running on worker node
      CEPO_URL: http://${WORKER_IP}:8080
      OPTILLM_BASE_URL: http://${WORKER_IP}:8080

  admin:
    environment:
      # Point to CePO running on worker node
      CEPO_URL: http://${WORKER_IP}:8080

  # Disable CePO on primary (runs on worker)
  cepo:
    profiles:
      - disabled
EOF

echo -e "${GREEN}✓${NC} Created docker-compose.override.yml pointing to worker CePO"

# =============================================================================
# RESTART PRIMARY SERVICES
# =============================================================================
echo -e "\n${YELLOW}[5/5]${NC} Restarting primary services with new configuration..."
cd "$PROJECT_ROOT"
docker compose up -d backend admin
echo -e "${GREEN}✓${NC} Primary services restarted"

# =============================================================================
# VERIFY DEPLOYMENT
# =============================================================================
echo -e "\n${YELLOW}Verifying deployment...${NC}"

echo -e "\n${BLUE}Primary containers:${NC}"
docker --context gogga-primary ps

echo -e "\n${BLUE}Worker containers:${NC}"
docker --context gogga-worker ps

# Test CePO health
echo -e "\n${YELLOW}Testing CePO health on worker...${NC}"
sleep 5
if curl -sf "http://${WORKER_IP}:8080/health" > /dev/null; then
    echo -e "${GREEN}✓${NC} CePO on worker is healthy!"
else
    echo -e "${YELLOW}!${NC} CePO may still be starting up. Check in a few seconds."
fi

echo -e "\n${GREEN}============================================${NC}"
echo -e "${GREEN}  Worker Deployment Complete!${NC}"
echo -e "${GREEN}============================================${NC}"
echo -e ""
echo -e "Services on ${BLUE}PRIMARY (192.168.0.130)${NC}:"
echo -e "  • Frontend:  http://localhost:3000"
echo -e "  • Backend:   http://localhost:8000"
echo -e "  • Admin:     http://localhost:3100"
echo -e ""
echo -e "Services on ${BLUE}WORKER (192.168.0.198)${NC}:"
echo -e "  • CePO:      http://${WORKER_IP}:8080"
echo -e "  • cAdvisor:  http://${WORKER_IP}:8081"
echo -e ""
echo -e "Shared storage: ${BLUE}/mnt/dev-drive${NC}"
