ignoredBuiltDependencies:
  - '@firebase/util'
  - '@prisma/engines'
  - core-js
  - esbuild
  - onnxruntime-node
  - prisma
  - protobufjs
  - rxdb
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@firebase/util'
  - better-sqlite3
  - core-js
  - esbuild
  - onnxruntime-node
  - protobufjs
  - rxdb
  - sharp
  - unrs-resolver
